### ISSUE TITLE
[Server Request] 新增小游戏服

### ISSUE THREAD

**Issue by Xanbert** [hit-mc/hitmc#1]
我也不知道是什么 反正先开个issue（

**Comment by inclyc** [comment]
Link https://github.com/hit-mc/hitmc/issues/2

讨论就玩家持久性上这两个服的可行性

**Comment by Phychias** [comment]
小游戏服的问题是，如果不是公开服务器，很难凑得齐人开一把游戏

**Comment by Phychias** [comment]
> 小游戏服的问题是，如果不是公开服务器，很难凑得齐人开一把游戏

而且没有积分榜之类的机制，小游戏服就只能是玩过就算了

**Comment by inclyc** [comment]
> 而且没有积分榜之类的机制，小游戏服就只能是玩过就算了

就我们以往开服的经验而言，小游戏服经常开一次玩不了多久就关了。

技术上很难实现已有的像Hypixel那样成熟的功能，勉强做了个起床战争又bug很多。感觉私服运营小游戏的还是比较少。

**Comment by inclyc** [comment]
> > 而且没有积分榜之类的机制，小游戏服就只能是玩过就算了
> 
> 就我们以往开服的经验而言，小游戏服经常开一次玩不了多久就关了。
> 
> 技术上很难实现已有的像Hypixel那样成熟的功能，勉强做了个起床战争又bug很多。感觉私服运营小游戏的还是比较少。

先这样吧，暂时就不开了。去开https://github.com/hit-mc/hitmc/issues/2 提到的养老服（最好真的养老）
