### ISSUE TITLE
在dragon服生命周期结束后，新增一个创造服

### ISSUE THREAD

**Issue by Phychias** [hit-mc/hitmc#17]
# 动机
鉴于之前有群友提出过想要一个创造服务器，而在dragon服结束之后，服务器应该能有一定空余的资源来支持这样一个服务器。所以我希望能开一个mod导向的创造服试试水。

# 具体内容
基于1.12.2多个创造装饰性模组打造一个整合包，能够做出相比原版更为精致的内容。
[一个典型的例子](https://www.bilibili.com/video/BV1LY4y1c7g4/?spm_id_from=333.999.0.0&vd_source=0aff0021c6113b55dedea845fb1bc79c)

# Modlist
一个可能的modlist，这个modlist有些臃肿，如果最终决定要开我会进行删减
![image](https://user-images.githubusercontent.com/51688899/194762307-1dd48108-1ec5-48f1-b4cd-a9d837fa7e87.png)

CC @SYjiuliang @Phychias @inclyc @yyezhi @alxndrt0512

**Comment by Phychias** [comment]
@yyezhi @alxndrt0512

**Comment by inclyc** [comment]
我觉得你可以在群里贴上这里的地址，这样大家知道你发了

**Comment by inclyc** [comment]
(草，点成close了

**Comment by inclyc** [comment]
这个服务器是临时性的还是常开？

**Comment by Phychias** [comment]
> 这个服务器是临时性的还是常开？

看反响和具体服务器消耗吧，如果可能的话可以开久一点，毕竟建筑也是相当花时间的

**Comment by SpiritedDragonet** [comment]
不管怎么说，强烈推荐加上龙之生存（dragon survival）模租
https://www.bilibili.com/video/BV1534y1B7Bv/?spm_id_from=333.999.0.0

**Comment by Phychias** [comment]
> 不管怎么说，强烈推荐加上龙之生存（dragon survival）模租 https://www.bilibili.com/video/BV1534y1B7Bv/?spm_id_from=333.999.0.0

但是这是个创造服啊

**Comment by inclyc** [comment]
生存向的有推荐吗？

**Comment by Phychias** [comment]
> 生存向的有推荐吗？

生存其实可以考虑机动星系，最近看直播觉得这个包相当精致，但是想等到我有空再来开。。。
其实我觉得可以考虑开一期rlcraft或者开个机动飞升

**Comment by inclyc** [comment]
> > 生存向的有推荐吗？
> 
> 生存其实可以考虑机动星系，最近看直播觉得这个包相当精致，但是想等到我有空再来开。。。 其实我觉得可以考虑开一期rlcraft或者开个机动飞升

来个issue~

**Comment by SpiritedDragonet** [comment]
挖藕，这个reply居然会直接发到个人邮箱里2333



在 2022-10-19 11:36:56，"inclyc" ***@***.***> 写道：

生存向的有推荐吗？

生存其实可以考虑机动星系，最近看直播觉得这个包相当精致，但是想等到我有空再来开。。。 其实我觉得可以考虑开一期rlcraft或者开个机动飞升

来个issue~

**Comment by inclyc** [comment]
Outdated
