### ISSUE TITLE
[Server Request]来自群友TsunamiCloud的dragon服替代方案

### ISSUE THREAD

**Issue by Phychias** [hit-mc/hitmc#18]
# 基于“机械动力：永无止境-重逢“整合包开一个新服务器替代dragon

- [mcmod帖子](https://www.mcmod.cn/modpack/465.html)

- 鉴于大伙对机械动力都还蛮感兴趣，并且创造服无人响应，故有此替代方案

CC @inclyc

**Comment by Tsunamicloud** [comment]
- 《重缝》/doge
- 此整合包目前为基于Quilt的Alpha版本（最新版无Fabric）
- 作者目前并未表现出将整合包适配PCL2的倾向

追求稳定的体验可能CAB或其他整合包更适合

btw 本部的mod服玩家感觉好少，大家有感兴趣的方向可以多提一提

**Comment by Phychias** [comment]
> * 《重缝》/doge
> * 此整合包目前为基于Quilt的Alpha版本（最新版无Fabric）
> * 作者目前并未表现出将整合包适配PCL2的倾向
> 
> 追求稳定的体验可能CAB或其他整合包更适合
> 
> btw 本部的mod服玩家感觉好少，大家有感兴趣的方向可以多提一提

没有服务端捏，而且我下了发现不会导入

**Comment by Tsunamicloud** [comment]
> 

那CAB或者机动星系？

**Comment by Phychias** [comment]
> > 
> 
> 那CAB或者机动星系？

已经部署，但mcdr未连接，待查
CC @inclyc @alxndrt0512

**Comment by inclyc** [comment]
> > > 
> > 
> > 
> > 那CAB或者机动星系？
> 
> 已经部署，但mcdr未连接，待查 CC @inclyc @alxndrt0512

可以补充一下文档
