### ISSUE TITLE
[Server Request] 一个新的养老服

### ISSUE THREAD

**Issue by kIm5R** [hit-mc/hitmc#2]
**描述你想创建的服务器内容**

综合考虑到部分不肝群友的时间精力有限和游玩意愿，以及前几个服的寿命问题，提出开设一个玩法完全相异于以往的新服。

**描述你的方案**

整合包的概述与建议玩法如下：
- 版本1.18.2 forge，优化较好(帧率拉满)，且作者一直在同步更新
- 主要内容是数量众多的动植物，自然风景优美，基本没有科技、魔法内容。减少敌对生物，保留了少量冒险元素(在下界和末地)，整体节奏较慢，适合养老。玩家在游戏中可以体验种植农作物，养殖动物，小规模的建筑与装饰，收集各种材料和卡牌，主打原始的农业社会。
- 不提倡在游戏中建造机器，保持纯手动小规模的生产，有利于保持慢节奏，护肝。预计平均每日游玩时间相对少，延长此服的生存周期。

**附加支撑材料**

附1：[整合包来源:Bilibili](https://www.bilibili.com/video/BV1w8411b7t2/?spm_id_from=333.788&vd_source=065f785a75f659c5633904562e0833a3)

附2：modlist 
![modlist截图](https://user-images.githubusercontent.com/115182660/194458814-6dc8b138-3c0d-484d-ad5f-38951b5d1bb9.png)

> CC @inclyc

**Comment by inclyc** [comment]
mod列表是否会太多了？我比较担心服务器占用

**Comment by Xanbert** [comment]
十分同意，并且建议以轻建筑为导向那种

**Comment by inclyc** [comment]
@Phychias

**Comment by Xanbert** [comment]
> mod列表是否会太多了？我比较担心服务器占用

目测并无大型mod 只要不出现bug问题就不大

**Comment by inclyc** [comment]
> > mod列表是否会太多了？我比较担心服务器占用
> 
> 目测并无大型mod 只要不出现bug问题就不大

主要是以前经常出现某个mod质量很低，最后死锁。要知道大量mc mod都是Java初学者写的

**Comment by leaveslifelove** [comment]
值得一试

**Comment by inclyc** [comment]
@SUIBING112233 1.18.2 Forge是否成熟？

**Comment by Krysztal112233** [comment]
> @SUIBING112233 1.18.2 Forge是否成熟？

1.18.2 forge相对成熟，modder之间默认该版本为下一个lts

**Comment by kIm5R** [comment]
补充：目标群体是空闲时间少，游玩节奏慢的休闲玩家，因此建议玩家事先自行匹配伙伴共同上线，以充分体验多人游玩的快乐

**Comment by Phychias** [comment]
> > > mod列表是否会太多了？我比较担心服务器占用

> > 目测并无大型mod 只要不出现bug问题就不大

> 主要是以前经常出现某个mod质量很低，最后死锁。要知道大量mc mod都是Java初学者写的

mod列表不算多，现在mod服跑的那个包比这个多，但这个modlist给我的感觉不怎么丰富，建议加上殖民地模组，这几天玩下来感觉还行

**Comment by Phychias** [comment]
> > > > mod列表是否会太多了？我比较担心服务器占用
> 
> > > 目测并无大型mod 只要不出现bug问题就不大
> 
> > 主要是以前经常出现某个mod质量很低，最后死锁。要知道大量mc mod都是Java初学者写的
> 
> mod列表不算多，现在mod服跑的那个包比这个多，但这个modlist给我的感觉不怎么丰富，建议加上殖民地模组，这几天玩下来感觉还行

另：这个整合的ftb有完善的任务系统吗

@kIm5R

**Comment by kIm5R** [comment]
> > > > > mod列表是否会太多了？我比较担心服务器占用
> > 
> > 
> > > > 目测并无大型mod 只要不出现bug问题就不大
> > 
> > 
> > > 主要是以前经常出现某个mod质量很低，最后死锁。要知道大量mc mod都是Java初学者写的
> > 
> > 
> > mod列表不算多，现在mod服跑的那个包比这个多，但这个modlist给我的感觉不怎么丰富，建议加上殖民地模组，这几天玩下来感觉还行
> 
> 另：这个整合的ftb有完善的任务系统吗
> 
> @kIm5R



有完整的任务树，任务描述，完成奖励都很详细。因此我不太希望另外增加玩法有差的大模组，在细节方面有实用的小模组倒是可以加进来
另<img width="419" alt="image" src="https://user-images.githubusercontent.com/115182660/194471949-5593644b-c185-4728-b9d9-87186b2cd90a.png">

**Comment by Phychias** [comment]
> > > > > > mod列表是否会太多了？我比较担心服务器占用

> > > > > 目测并无大型mod 只要不出现bug问题就不大

> > > > 主要是以前经常出现某个mod质量很低，最后死锁。要知道大量mc mod都是Java初学者写的

> > > mod列表不算多，现在mod服跑的那个包比这个多，但这个modlist给我的感觉不怎么丰富，建议加上殖民地模组，这几天玩下来感觉还行

> > 另：这个整合的ftb有完善的任务系统吗

> > @kIm5R

> 有完整的任务树，任务描述，完成奖励都很详细。因此我不太希望另外增加玩法有差的大模组，在细节方面有实用的小模组倒是可以加进来 另<img alt="image" width="419" src="https://user-images.githubusercontent.com/115182660/194471949-5593644b-c185-4728-b9d9-87186b2cd90a.png">

加个殖民地模组挺好的，那个东西不怎么改变大的玩法，你可以去看一下那个模组具体玩法，那个模组可玩性相当高。

**Comment by inclyc** [comment]
> 加个殖民地模组挺好的，那个东西不怎么改变大的玩法

有点类似圈地？

**Comment by Phychias** [comment]
> > 加个殖民地模组挺好的，那个东西不怎么改变大的玩法
> 
> 有点类似圈地？

实际上是一个强化过的村庄模组，有一定rpg和自动化的成分在里面，但是同时又不算太肝，而且最终出来的效果很好看，因为你可以不用过多的操作就起很多很漂亮的建筑。这个模组也是我推荐自然主义整合包的一个重要原因，这个模组很适合养老。可以让找不到一起联机的人跟村民玩hh。

**Comment by Phychias** [comment]
PS： 殖民地模组的链接

https://minecolonies.com/
https://www.mcmod.cn/class/682.html
https://github.com/ldtteam/minecolonies

**Comment by inclyc** [comment]
> 实际上是一个强化过的村庄模组，有一定rpg和自动化的成分在里面，但是同时又不算太肝，而且最终出来的效果很好看，因为你可以不用过多的操作就起很多很漂亮的建筑。

从我个人的喜好来看，可能更希望偏养老的服务器越“简单”越好

**Comment by Phychias** [comment]
> > 实际上是一个强化过的村庄模组，有一定rpg和自动化的成分在里面，但是同时又不算太肝，而且最终出来的效果很好看，因为你可以不用过多的操作就起很多很漂亮的建筑。
> 
> 从我个人的喜好来看，可能更希望偏养老的服务器越“简单”越好

ww主要这个包缺少一个比较好的建筑相关模组。
个人认为需要一定的建筑要素比较好留住玩家。mc很大一部分魅力就来自建筑，但建筑的门槛相对又比较高，通过这个模组可以实现一些轻度的建筑、城市规划的同时，能收获一定量的产物，而这产物的量也不会形成无法融入的技术壁垒

**Comment by Phychias** [comment]
> > 实际上是一个强化过的村庄模组，有一定rpg和自动化的成分在里面，但是同时又不算太肝，而且最终出来的效果很好看，因为你可以不用过多的操作就起很多很漂亮的建筑。
> 
> 从我个人的喜好来看，可能更希望偏养老的服务器越“简单”越好

ww主要这个包缺少一个比较好的建筑相关模组。
个人认为需要一定的建筑要素比较好留住玩家。mc很大一部分魅力就来自建筑，但建筑的门槛相对又比较高，通过这个模组可以实现一些轻度的建筑、城市规划的同时，能收获一定量的产物，而这产物的量也不会形成无法融入的技术壁垒

**Comment by inclyc** [comment]
主要我对mod这种“整合”了解不多，你要觉得有必要加就加吧。

在 2022/10/7 15:49, Phychias 写道:

**Comment by inclyc** [comment]
@SUIBING112233 WDYT?

**Comment by Krysztal112233** [comment]
简单观察了一下mod列表，加入模拟殖民地可能是个好选择，因为对于玩家来讲搭建建筑物不是所有人都会的事情。

但是对于整合包的平衡性有待商议

**Comment by inclyc** [comment]
> 但是对于整合包的平衡性有待商议

有mod影响平衡？

**Comment by Phychias** [comment]
> > 但是对于整合包的平衡性有待商议
> 
> 有mod影响平衡？

应该是指殖民地模组对游戏平衡性的影响

**Comment by inclyc** [comment]
@Phychias @SUIBING112233  你们俩的review意见是什么？

**Comment by Krysztal112233** [comment]
> > > 但是对于整合包的平衡性有待商议
> > 
> > 
> > 有mod影响平衡？
> 
> 应该是指殖民地模组对游戏平衡性的影响

是，因为不清楚是否会加快整合包游玩节奏等，需要发起人确认是否有影响

**Comment by Phychias** [comment]
> @Phychias @SUIBING112233 你们俩的review意见是什么？

我认为可以一试

**Comment by Krysztal112233** [comment]
我认为这是一次有益的尝试

**Comment by Phychias** [comment]
@kIm5R 整合包测试做完了吗

**Comment by inclyc** [comment]
好耶

**Comment by inclyc** [comment]
本地似乎成功跑起来了

**Comment by kIm5R** [comment]
现在是什么进度了，我有点懵。。。。
关于这个mod，基本上是独立的，也就是说单从游戏游玩角度来说有无并不影响原有玩法。但是强调一点的是，由于原设定是一个非常安全的环境，所以玩家在建造殖民地mod的建筑时切记远离原居住点，以免受到其敌对生物的影响。

**Comment by inclyc** [comment]
> 关于这个mod，基本上是独立的

“这个mod”是什么mod，殖民地吗？

于 2022年10月7日 GMT+08:00 下午6:19:31, kIm5R ***@***.***> 写到:

**Comment by kIm5R** [comment]
> 关于这个mod，基本上是独立的
> “这个mod”是什么mod，殖民地吗？ 于 2022年10月7日 GMT+08:00 下午6:19:31, kIm5R ***@***.***> 写到:
> […](#)
> 现在是什么进度了，我有点懵。。。。 关于这个mod，基本上是独立的，也就是说单从游戏游玩角度来说有无并不影响原有玩法。但是强调一点的是，由于原设定是一个非常安全的环境，所以玩家在建造殖民地mod的建筑时切记远离原居住点，以免受到其敌对生物的影响。 -- Reply to this email directly or view it on GitHub: [#2 (comment)](https://github.com/hit-mc/hitmc/issues/2#issuecomment-1271406566) You are receiving this because you were mentioned. Message ID: ***@***.***>

对对对，殖民地。忘记点回复了

**Comment by Phychias** [comment]
> > 关于这个mod，基本上是独立的
> > “这个mod”是什么mod，殖民地吗？ 于 2022年10月7日 GMT+08:00 下午6:19:31, kIm5R _**@**_._**> 写到:
> > […](#)
> > 现在是什么进度了，我有点懵。。。。 关于这个mod，基本上是独立的，也就是说单从游戏游玩角度来说有无并不影响原有玩法。但是强调一点的是，由于原设定是一个非常安全的环境，所以玩家在建造殖民地mod的建筑时切记远离原居住点，以免受到其敌对生物的影响。 -- Reply to this email directly or view it on GitHub: [#2 (comment)](https://github.com/hit-mc/hitmc/issues/2#issuecomment-1271406566) You are receiving this because you were mentioned. Message ID: _**@**_.**_>
> 
> 对对对，殖民地。忘记点回复了

今天刚打过，这模组的敌对生物靠村民自己就够了，无需担心

**Comment by inclyc** [comment]
> > > 关于这个mod，基本上是独立的
> > > “这个mod”是什么mod，殖民地吗？ 于 2022年10月7日 GMT+08:00 下午6:19:31, kIm5R _**@**_._**> 写到:
> > > […](#)
> > > 现在是什么进度了，我有点懵。。。。 关于这个mod，基本上是独立的，也就是说单从游戏游玩角度来说有无并不影响原有玩法。但是强调一点的是，由于原设定是一个非常安全的环境，所以玩家在建造殖民地mod的建筑时切记远离原居住点，以免受到其敌对生物的影响。 -- Reply to this email directly or view it on GitHub: [#2 (comment)](https://github.com/hit-mc/hitmc/issues/2#issuecomment-1271406566) You are receiving this because you were mentioned. Message ID: _**@**_.**_>
> > 
> > 
> > 对对对，殖民地。忘记点回复了
> 
> 今天刚打过，这模组的敌对生物靠村民自己就够了，无需担心

九亮为什么不评论啊（

**Comment by Phychias** [comment]
可以考虑部署服务端，我会把殖民地模组加进去并为他更新

**Comment by inclyc** [comment]
> 可以考虑部署服务端，我会把殖民地模组加进去并为他更新

没有给我服务端（

**Comment by Phychias** [comment]
> > 可以考虑部署服务端，我会把殖民地模组加进去并为他更新
> 
> 没有给我服务端（

@kIm5R

**Comment by SYjiuliang** [comment]
我投票赞成，还有或者说要不要BC一下AB的跑酷地图的说

**Comment by inclyc** [comment]
> 我投票赞成，还有或者说要不要BC一下AB的跑酷地图的说

https://github.com/hit-mc/hitmc/issues/6 在这里讨论

**Comment by inclyc** [comment]
我已把服务端上传到物理机，@Phychias 部署一下？可以共用`TMUX` + 语音，帮你看着

**Comment by Phychias** [comment]
> 我已把服务端上传到物理机，@Phychias 部署一下？可以共用`TMUX` + 语音，帮你看着

可，那要关掉原版服务器吗

**Comment by inclyc** [comment]
'[Xaero的小地图] Xaeros_Minimap_22.14.1_Forge_1.18.2.jar'
'[龙骑士重置版] dragonmounts-1.18.2-1.1.4.jar'
'[苹果皮] appleskin-forge-mc1.18.2-2.4.1.jar'
'[车万女仆] touhoulittlemaid-1.18.2-1.0.0-alpha.jar'


这些是服务端必要的吗？ @kIm5R 

@SUIBING112233 能否看一下是否有多余/奇怪的mod

我的建议是重新审核mod的必要性

**Comment by inclyc** [comment]
我的意见是最好从纯净服开始加东西，写清楚mod的需求和功能，为什么需要。

我们刚刚甚至在服务端mod列表里看到了自动钓鱼

**Comment by kIm5R** [comment]
> '[Xaero的小地图] Xaeros_Minimap_22.14.1_Forge_1.18.2.jar' '[龙骑士重置版] dragonmounts-1.18.2-1.1.4.jar' '[苹果皮] appleskin-forge-mc1.18.2-2.4.1.jar' '[车万女仆] touhoulittlemaid-1.18.2-1.0.0-alpha.jar'
> 
> 这些是服务端必要的吗？ @kIm5R
> 
> @SUIBING112233 能否看一下是否有多余/奇怪的mod
> 
> 我的建议是重新审核mod的必要性

四个mod的描述如下
右上角小地图实时显示平面地图，生物分布，位置信息，必要性：很大
提供龙蛋的孵化，龙的驯服和骑乘
提供食物效果在血量饱食度饱和度上更直观的展示，建议保留
提供女仆

**Comment by inclyc** [comment]
> > '[Xaero的小地图] Xaeros_Minimap_22.14.1_Forge_1.18.2.jar' '[龙骑士重置版] dragonmounts-1.18.2-1.1.4.jar' '[苹果皮] appleskin-forge-mc1.18.2-2.4.1.jar' '[车万女仆] touhoulittlemaid-1.18.2-1.0.0-alpha.jar'
> > 这些是服务端必要的吗？ @kIm5R
> > @SUIBING112233 能否看一下是否有多余/奇怪的mod
> > 我的建议是重新审核mod的必要性
> 
> 四个mod的描述如下 右上角小地图实时显示平面地图，生物分布，位置信息，必要性：很大 提供龙蛋的孵化，龙的驯服和骑乘 提供食物效果在血量饱食度饱和度上更直观的展示，建议保留 提供女仆

这是客户端mod吧，跟服务端没啥关系吧。

**Comment by inclyc** [comment]
怎么还有CustomSkinLoader啊

**Comment by kIm5R** [comment]
> 我的意见是最好从纯净服开始加东西，写清楚mod的需求和功能，为什么需要。
> 
> 我们刚刚甚至在服务端mod列表里看到了自动钓鱼

因为做整合包不仅仅是mod的叠加，这是从原版直接加mod无法实现的。然后这个服务端mod列表应该是直接拿单人的mod列表复制过去的

**Comment by inclyc** [comment]
> 因为做整合包不仅仅是mod的叠加，这是从原版直接加mod无法实现的。

？你是指ftb的什么指南吗

> 原版直接加mod

那服务端作者是怎么做的服务端？

> 然后这个服务端mod列表应该是直接拿单人的mod列表复制过去的

显然不应该复制单人的Mod列表

**Comment by kIm5R** [comment]
> > 因为做整合包不仅仅是mod的叠加，这是从原版直接加mod无法实现的。
> 
> ？你是指ftb的什么指南吗
> 
> > 原版直接加mod
> 
> 那服务端作者是怎么做的服务端？
> 
> > 然后这个服务端mod列表应该是直接拿单人的mod列表复制过去的
> 
> 显然不应该复制单人的Mod列表

就是很多mod改了参数，或者去除mod中一部分的内容来保持平衡性，汉化，还有就是任务什么什么的那些

**Comment by inclyc** [comment]
## 显然不应该复制单人的Mod列表

**Comment by Phychias** [comment]
> > > 因为做整合包不仅仅是mod的叠加，这是从原版直接加mod无法实现的。
> > 
> > 
> > ？你是指ftb的什么指南吗
> > > 原版直接加mod
> > 
> > 
> > 那服务端作者是怎么做的服务端？
> > > 然后这个服务端mod列表应该是直接拿单人的mod列表复制过去的
> > 
> > 
> > 显然不应该复制单人的Mod列表
> 
> 就是很多mod改了参数，或者去除mod中一部分的内容来保持平衡性，汉化，还有就是任务什么什么的那些

感觉这个包没改啥参数，不知道mod的兼容性如何

**Comment by Krysztal112233** [comment]
> > > '[Xaero的小地图] Xaeros_Minimap_22.14.1_Forge_1.18.2.jar' '[龙骑士重置版] dragonmounts-1.18.2-1.1.4.jar' '[苹果皮] appleskin-forge-mc1.18.2-2.4.1.jar' '[车万女仆] touhoulittlemaid-1.18.2-1.0.0-alpha.jar'
> > > 这些是服务端必要的吗？ @kIm5R
> > > @SUIBING112233 能否看一下是否有多余/奇怪的mod
> > > 我的建议是重新审核mod的必要性
> > 
> > 
> > 四个mod的描述如下 右上角小地图实时显示平面地图，生物分布，位置信息，必要性：很大 提供龙蛋的孵化，龙的驯服和骑乘 提供食物效果在血量饱食度饱和度上更直观的展示，建议保留 提供女仆
> 
> 这是客户端mod吧，跟服务端没啥关系吧。

除了第一项，其他都是服务器需要安装

**Comment by kIm5R** [comment]
> > 因为做整合包不仅仅是mod的叠加，这是从原版直接加mod无法实现的。
> 
> ？你是指ftb的什么指南吗
> 
> > 原版直接加mod
> 
> 那服务端作者是怎么做的服务端？
> 
> > 然后这个服务端mod列表应该是直接拿单人的mod列表复制过去的
> 
> 显然不应该复制单人的Mod列表

也就是说现在把仅需客户端的mod删除就ok吧，有什么影响吗？

**Comment by inclyc** [comment]
> > > > '[Xaero的小地图] Xaeros_Minimap_22.14.1_Forge_1.18.2.jar' '[龙骑士重置版] dragonmounts-1.18.2-1.1.4.jar' '[苹果皮] appleskin-forge-mc1.18.2-2.4.1.jar' '[车万女仆] touhoulittlemaid-1.18.2-1.0.0-alpha.jar'
> > > > 这些是服务端必要的吗？ @kIm5R
> > > > @SUIBING112233 能否看一下是否有多余/奇怪的mod
> > > > 我的建议是重新审核mod的必要性
> > > 
> > > 
> > > 四个mod的描述如下 右上角小地图实时显示平面地图，生物分布，位置信息，必要性：很大 提供龙蛋的孵化，龙的驯服和骑乘 提供食物效果在血量饱食度饱和度上更直观的展示，建议保留 提供女仆
> > 
> > 
> > 这是客户端mod吧，跟服务端没啥关系吧。
> 
> 除了第一项，其他都是服务器需要安装

从我个人的体验来看希望mod尽量精简，这个服的占用感觉都跟一个正常模组服差不多了

**Comment by Phychias** [comment]
> > > 因为做整合包不仅仅是mod的叠加，这是从原版直接加mod无法实现的。
> > 
> > 
> > ？你是指ftb的什么指南吗
> > > 原版直接加mod
> > 
> > 
> > 那服务端作者是怎么做的服务端？
> > > 然后这个服务端mod列表应该是直接拿单人的mod列表复制过去的
> > 
> > 
> > 显然不应该复制单人的Mod列表
> 
> 也就是说现在把仅需客户端的mod删除就ok吧，有什么影响吗？

主要是这个服务端给人一种很不靠谱的感觉

**Comment by Krysztal112233** [comment]
若是删除 FTB 上列出的内容外的模组应该不会很影响。

正常的能用作启动服务器的整合包应当提供对应的Server Pack而不是让用户自己做，像是`Create: Above And Beyond Server Pack`

不过正常来讲不需要在服务端运作的模组会自己不加载，这部分开销可以不用太担心。


以及从另外一方面来说，Server Pack不可以只是简简单单的复制mod list，而应当判断模组所需要的具体文件夹最后一起放入。

因为 FTB 和 KubeJS 之流都有额外的文件夹需要一起放入。

**Comment by inclyc** [comment]
车万女仆能不要吗

**Comment by SUIBING112233** [comment]
以及从另外一方面来说，Server Pack不可以只是简简单单的复制mod list，而应当判断模组所需要的具体文件夹最后一起放入。

因为 FTB 和 KubeJS 之流都有额外的文件夹需要一起放入。

**Comment by inclyc** [comment]
> 以及从另外一方面来说，Server Pack不可以只是简简单单的复制mod list，而应当判断模组所需要的具体文件夹最后一起放入。
> 
> 因为 FTB 和 KubeJS 之流都有额外的文件夹需要一起放入。

乐，那现在怎么办

**Comment by Krysztal112233** [comment]
最简单的方法，就是直接拷贝配置文件夹 数据文件夹 mod文件夹，使用同版本的forge开个服务器。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: inclyc ***@***.***>
发送时间: Friday, October 7, 2022 11:07:17 PM
收件人: hit-mc/hitmc ***@***.***>
抄送: Krysztal ***@***.***>; Mention ***@***.***>
主题: Re: [hit-mc/hitmc] [Server Request] 一个新的养老服 (Issue #2)


以及从另外一方面来说，Server Pack不可以只是简简单单的复制mod list，而应当判断模组所需要的具体文件夹最后一起放入。

因为 FTB 和 KubeJS 之流都有额外的文件夹需要一起放入。

乐，那现在怎么办

―

**Comment by kIm5R** [comment]
好像这个作者又是单独做的服务端，刚刚看了客户端的mod确实更多一些

**Comment by inclyc** [comment]
> 好像这个作者又是单独做的服务端，刚刚看了客户端的mod确实更多一些

能否来一个干净的服务端（最好）

然后再发给我一个客户端（第二封邮件）

**Comment by Krysztal112233** [comment]
若是需要自己制作 Server Pack 可以考虑移除的mod

- [ ] 自定义局域网联机 该mod为客户端本地开服使用
- [ ] 万用皮肤补丁 已有Yggdrasil服务，不再需要
- [ ] FPS减速器 客户端挂机使用
- [ ] 鼠标手势 客户端模组

**Comment by kIm5R** [comment]
> > 好像这个作者又是单独做的服务端，刚刚看了客户端的mod确实更多一些
> 
> 能否来一个干净的服务端（最好）
> 
> 然后再发给我一个客户端（第二封邮件）

能否详细描述下要求，我抽时间搞一下

**Comment by inclyc** [comment]
> > > 好像这个作者又是单独做的服务端，刚刚看了客户端的mod确实更多一些
> > 
> > 
> > 能否来一个干净的服务端（最好）
> > 然后再发给我一个客户端（第二封邮件）
> 
> 能否详细描述下要求，我抽时间搞一下

按照@SUIBING112233 的建议修改一下服务端Mod列表，尽量精简服务端

提交前，确保本地能

- 正常开服
- 客户端能连上
- 服务端要坚持一段时间不崩溃，不输出刷屏等奇怪内容

--------------------

其实也还好，我们直接开吧

**Comment by Phychias** [comment]
服务器已部署
单人接入无异常

**Comment by inclyc** [comment]
> > > 好像这个作者又是单独做的服务端，刚刚看了客户端的mod确实更多一些
> > 
> > 
> > 能否来一个干净的服务端（最好）
> > 然后再发给我一个客户端（第二封邮件）
> 
> 能否详细描述下要求，我抽时间搞一下

@kIm5R @alxndrt0512  @SUIBING112233  测试一下 pub.rtr.hitmc.cc 是否可以进入？

**Comment by Phychias** [comment]
好消息是，这整合有自动建筑模组

**Comment by inclyc** [comment]
已完成，后续就是更新一下`README`文档就行了！

Link: https://github.com/hit-mc/hitmc/issues/7
