### ISSUE TITLE
[Server Request] 跑酷服务器

### ISSUE THREAD

**Issue by inclyc** [hit-mc/hitmc#6]
**描述你想创建的服务器内容**

用[velocity](https://velocitypowered.com/)连接来自AB(@MYHZZD)的跑酷服务器

可能出现的问题：

- 你服目前是直连生存，velocity对于1.19的支持和1.19本身的反向代理支持不完全。
- 延迟，我们的velocity开在物理机，而不是隧道。再加一层跳板的话延迟几乎是无法接受的。

**描述你的方案**

连接跑酷服务器，用velocity

**附加支撑材料**

CC @MYHZZD @SYjiuliang @inclyc @SUIBING112233

**Comment by SYjiuliang** [comment]
确实，暂时velocity有点大问题
或者跑酷可以作为一次活动来进行实现（）

**Comment by inclyc** [comment]
> 确实，暂时velocity有点大问题

就之前的经验来看，至少有如下问题，比较影响体验：

- 红木无法正确显示
- 青蛙无法正确显示
- 跨维度会崩溃

>  或者跑酷可以作为一次活动来进行实现（）

但感觉那样的话就不适合用长期跑酷地图了。我在b站看到过一些专门的通关性质的跑酷地图

比如[这个螺旋塔](https://www.bilibili.com/video/BV1Dt411j78H/?spm_id_from=333.337.search-card.all.click&vd_source=e59647671e1fd9b3e5d3aff985dcb45f)，还有一些结合弓箭的跑酷，感觉也不错。
